version: "3.9"
services:
  mysqlDb:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pw
      - MYSQL_DATABASE=product_db
      - MYSQL_ROOT_PASSWORD=pw
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - backend

  app:
    depends_on:
      mysqlDb:
        condition: service_healthy
    container_name: ProductServiceApplication
    restart: unless-stopped
    command: java -jar target/ProductServiceApplication-0.0.1-SNAPSHOT.jar
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8082:8082
    expose:
      - 8082
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqlDb:3306/product_db?autoReconnect=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=pw
    volumes:
      - ./:/app/app
    networks:
      - backend

networks:
  backend:
    name: KBE
    external: true
