server:
  port: 8082

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/product_db
    username: user
    password: pw

  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  rabbitmq:
    host: rabbitmq
    port: 5672
  redis:
    host: redis
    port: 6379



#rabbitMQ
queue-names:
  product-service: product-service.rpc.queue

routing-keys:
  product-service: product-service.rpc.key

xchange:
  name: exchange.rpc



