server:
  port: 8082

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/product_db
    username: user
    password: pw

  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

#rabbitMQ
queue-names:
  product-service: components.rpc.queue
  user-products: user-products.rpc.queue

routing-keys:
  product-service: components.rpc.key
  user-products: user-products.rpc.key

xchange:
  name: exchange.rpc


